require('lualine').setup{
    options={
        icons_enabled=true,
        theme='base16',
        component_separators={left='|',right='|'},
        section_separators={left='',right=''},
    },
    sections={
        lualine_a={'mode'},
        lualine_b={'branch','diff'},
        lualine_c={''},
        lualine_x={'encoding','fileformat','windows'},
        lualine_y={'progress'},
        lualine_z={'location'}
    },
}
